### ISSUE TITLE
HRNet or HrHRnet, which backbone do you use?

### ISSUE THREAD

**Issue by hellojialee** [HRNet/DEKR#10]
Hi~ Your paper uses HRNet while this repo seems to use HrHRNet at https://github.com/HRNet/DEKR/blob/b3904a4a3861c912d07c8294530772af33bda578/lib/models/hrnet_dekr.py#L33

Could you help me figure it out? Thanks!

**Comment by Gengzigang** [comment]
We use HRNet backbone. Thank you for pointing out the typo in the naming.
