### ISSUE TITLE
about backbone

### ISSUE THREAD

**Issue by shanyun123456** [HRNet/DEKR#11]
why don't you use lite-hrnet as your backbone？ limited performence or lite-hrnet  isn't suitable in this paper

**Comment by Gengzigang** [comment]
The lite-hrnet and our DEKR are concurrent work (CVPR2021). Our work was completed earlier, so we did not try to use the lite-hrnet.

**Comment by shanyun123456** [comment]
so have you test the performance of combination of lite-hrnet and your dekr, or  whether it is suitable to dekr?

**Comment by Gengzigang** [comment]
Hi, you can try it if you are interested in it. We believe that our approach can bring a large gain above the lite-hrnet regression baseline.
