### ISSUE TITLE
inference_demo.py csv_header little bug

### ISSUE THREAD

**Issue by yyccli** [HRNet/DEKR#15]
Hi, in inference_demo.py line 268, when `DATASET_TEST == 'crowdpose'`, the csv_header should use `CROWDPOSE_KEYPOINT_INDEXES` but not `COCO_KEYPOINT_INDEXES`. It's a little bug though the headers don't really matters ;)

**Comment by Gengzigang** [comment]
Hi, thanks for your suggestion.
