### ISSUE TITLE
Exhausted GPU memory with batch size of 1

### ISSUE THREAD

**Issue by wmcnally** [HRNet/DEKR#16]
I have 12GB of GPU memory (Titan Xp) and I ran out of memory using a batch size of 1 (when running valid.py). Is this expected? Thanks.

**Comment by Gengzigang** [comment]
Hi, I think the code can run on Titan Xp. You can check other settings.

**Comment by wmcnally** [comment]
Not sure what happened... It appears to be working now and only consuming ~3.6 GB of memory.
