### ISSUE TITLE
About AdaptBlock

### ISSUE THREAD

**Issue by captainfffsama** [HRNet/DEKR#21]
I notice that in the implement of AdaptBlock at [line 126](https://github.com/HRNet/DEKR/blob/9b667ad28ffe67349efe1381b2b4e7fbb6747da8/lib/models/conv_block.py#L126) show that:

```python
        offset = torch.matmul(transform_matrix, self.regular_matrix)
        offset = offset-self.regular_matrix
        offset = offset.transpose(1,2).reshape((N,H,W,18)).permute(0,3,1,2)
```

why offset need subtract self.regular_matrix ?

**Comment by Gengzigang** [comment]
Hi, you can check the CUDA code of the deformable convolution. The deformable convolution will add a regular matrix when it calculates the offset.
