### ISSUE TITLE
When I was training the scoring net, model/pose_coco/pose_dekr_hrnetw32_coco.pth in the command could not be found. It was a file, so I changed it to ‘output/coco_kpt/hrnet_dekr/w32_4x_reg03_bs10_512_adam_lr1e-3_coco_x140/final_state0.pth.tar’. is this command correct, because he reported an error that the picture size is inconsistent? I can't find how to change the picture size. Please help me solve it~

### ISSUE THREAD

**Issue by LiPan123456789** [HRNet/DEKR#29]
![image](https://user-images.githubusercontent.com/97578468/149438995-db6a67fc-7281-4802-b6ec-f5a3bd276e7a.png)
![image](https://user-images.githubusercontent.com/97578468/149439060-70f89f33-9005-4db1-b900-fb77d7b040c7.png)

![image](https://user-images.githubusercontent.com/97578468/149438921-f7555b75-e25c-4396-8904-4c85afc71466.png)
![image](https://user-images.githubusercontent.com/97578468/149438943-c196a3f8-dd18-4ec1-acae-027f4276caa4.png)

![image](https://user-images.githubusercontent.com/97578468/149438890-07a830b8-df52-4690-a7be-b31ce448afa1.png)

**Comment by Gengzigang** [comment]
You should use batchsize=1 in the inference process.

**Comment by LiPan123456789** [comment]
The problem was solved successfully, but I want to know why.

**Comment by Gengzigang** [comment]
The input size of each image during inference is different.

**Comment by LiPan123456789** [comment]
Thank you very much.
