### ISSUE TITLE
Unable to download the trained model

### ISSUE THREAD

**Issue by Yliqiang** [HRNet/DEKR#4]
Unable to download the trained model POSE_DEKR_HRNETW32.pth

**Comment by Vbird-ML** [comment]
I met the same problem.
have you solved it?

**Comment by Gengzigang** [comment]
Hi, I download it on my device successfully. I think that you can retry it.

**Comment by rrrepsac** [comment]
i suppose it's a misprint. use pose_dekr_hrnetw32_crowdpose.pth instead
