### ISSUE TITLE
Why not use mosaic, Have you tried it?  为什么不使用马赛克增强，有试过吗

### ISSUE THREAD

**Issue by a1802lzw** [HRNet/DEKR#43]
Have you ever used mosaic in your work and how effective have they been?

**Comment by Gengzigang** [comment]
We do not try this augmentation to keep fair with the previous works. I think it can bring the gain for our approach. You can try it.

**Comment by a1802lzw** [comment]
> We do not try this augmentation to keep fair with the previous works. I think it can bring the gain for our approach. You can try it.

Thanks for replying!, I'll try
