### ISSUE TITLE
Confidence score for each joint

### ISSUE THREAD

**Issue by anas-zafar** [HRNet/DEKR#44]
Thank you for the amazing work! I am looking to access the confidence score for each joint in the model. Can you please guide me how can I do that? Thanks @Gengzigang

**Comment by Gengzigang** [comment]
You can find it in this file: https://github.com/HRNet/DEKR/blob/main/lib/core/nms.py

**Comment by anas-zafar** [comment]
@Gengzigang if I am correct,  `poses = pose_nms(cfg, heatmap_avg, poses)` contains the confidence score of the 17 keypoints and x,y cordinates
