### ISSUE TITLE
testing on a custom dataset

### ISSUE THREAD

**Issue by gvreergo** [HRNet/DEKR#5]
Hi!
First thanks for your work that show magnificient results.

I would like to use your model on a custom dataset to try out if it is efficient on my challenging pictures. Could you tell what are the different step ?

Thanks a lot!

**Comment by Gengzigang** [comment]
Hi, I think if you just want to replace coco dataset with your custom dataset, you only need to change the dataset code to load your dataset and adjust the num_joint parameter. In addition, you can alternatively train the rescore model for your dataset. The rescore model can also be removed and the performance does not change a lot.

**Comment by gvreergo** [comment]
thank you for your help !

I had to modify something on lib/dataset/COCOdataset.py  

because my filenames were not only with numbers i had to make some changes :

Every time ```int( filename[-16:-4 ] )```  showed i replaced it by  ```img_id```

example : 
```
 kpts[img_id].append(
                    {
                        'keypoints': kpt[:, 0:3],
                        'score': scores[idx][idx_kpt],
                        'image': img_id,
                        'area': area
                    }```

thanks for your help !
