### ISSUE TITLE
ValueError: desired inference fps is 10 but video fps is 0.0

### ISSUE THREAD

**Issue by yiweike** [HRNet/DEKR#8]
When i run "python tools/inference_demo.py --cfg experiments/coco/inference_demo_coco.yaml \
    --videoFile ../multi_people.mp4 \
    --outputDir output \
    --visthre 0.3 \
    TEST.MODEL_FILE model/pose_coco/pose_dekr_hrnetw32.pth"
I get error:
  Traceback (most recent call last):
  File "tools/inference_demo.py", line 286, in <module>
    main()
  File "tools/inference_demo.py", line 208, in main
    str(args.inferenceFps)+' but video fps is '+str(fps))
ValueError: desired inference fps is 10 but video fps is 0.0
can you tell me why and how to slove the problem

**Comment by Gengzigang** [comment]
I am sorry that I can not reproduce your error. I guess that the reason is that there is a problem with the video format. Maybe you can try other videos.

**Comment by yiweike** [comment]
Thanks for your reply, i used another video and it worked.
