### ISSUE TITLE
The evaluation result of my running is not good

### ISSUE THREAD

**Issue by asahiruyoru** [HRNet/DEKR#9]
Hello, Thank for your great work.

I ran the evaluation code with your public trained model following your readme,
but the result is different from your paper.

| Arch | AP | Ap .5 | AP .75 | AP (M) | AP (L) | AR | AR .5 | AR .75 | AR (M) | AR (L) |
|---|---|---|---|---|---|---|---|---|---|---|
| hrnet_dekr | 0.365 | 0.484 | 0.400 | 0.335 | 0.463 | 0.684 | 0.844 | 0.732 | 0.619 | 0.778 |

Could you tell me that any error is in the code?
The code is  https://github.com/asahiruyoru/dekr_eval

**Comment by Gengzigang** [comment]
Hi, I just cloned the code, downloaded the trained model and tested it. The result is the same as my paper.
I compared the two log files and found that the configs are exactly the same. 
I found that your DEKR directory had existed when you cloned the code. I want to know if you have modified the code?

**Comment by asahiruyoru** [comment]
Thank you for your quick reply, and I'm sorry for my late reply.

DEKR directory is cloned every time.
Restarting colab session is required to use the suitable version of numpy written ​in requirements.txt.
DEKR is cloned before restarting, so I added "if not os.path.exists('DEKR')"
But it is confusing, so I uploaded modified version of notebook, https://github.com/asahiruyoru/dekr_eval/blob/main/eval_v2.ipynb

I modified your code a little because it occurred the following error.
> FileNotFoundError: [Errno 2] No such file or directory: 'model/rescore/final_rescore_coco_kpt.pth'
To avoid the error, I made a symlink between the path and "models/pose_coco/pose_dekr_hrnetw32_coco.pth".

I would appreciate it if you could find my mistake and tell me it.

**Comment by Gengzigang** [comment]
Hi, your process in the notebook is correct. I think you modified the code. I would like to ask if you can share your code?

**Comment by Gengzigang** [comment]
Hi, I think the symlink is a little strange, this two models are totally different. I am curious how you can run the code successfully and why the results of two experiments are different. 
`os.symlink("../../models/pose_coco/pose_dekr_hrnetw32_coco.pth", "model/rescore/final_rescore_coco_kpt.pth")`
By the way, this models are provided in my Onedrive.

**Comment by asahiruyoru** [comment]
Thank you for checking my code and reply.
I misunderstood about a scoring net.  After downloading and using those models, I got the same result.

**Comment by Gengzigang** [comment]
The scoring net does not influence so much. The AP only drops about 0.5 without it.
